// File that holds the constants for ESPN related data
// Taken from: https://fantasy.espn.com/football/boxscore?leagueId=1422028&matchupPeriodId=2&scoringPeriodId=2&seasonId=2020&teamId=8&view=scoringperiod:formatted
constants = {
  "lineupSlots": [{
    "abbrev": "QB",
    "active": true,
    "bench": false,
    "canApplyLimitIndividually": false,
    "display": true,
    "displayOrder": 1,
    "eligiblePositions": [1],
    "id": 0,
    "injuryRequired": false,
    "lineupSlotEligible": true,
    "name": "Quarterback",
    "parentId": 7,
    "starter": true
  }, {
    "abbrev": "TQB",
    "active": true,
    "bench": false,
    "canApplyLimitIndividually": false,
    "display": true,
    "displayOrder": 2,
    "eligiblePositions": [15],
    "id": 1,
    "injuryRequired": false,
    "lineupSlotEligible": true,
    "name": "Team Quarterback",
    "parentId": 7,
    "starter": true
  }, {
    "abbrev": "RB",
    "active": true,
    "bench": false,
    "canApplyLimitIndividually": false,
    "display": true,
    "displayOrder": 3,
    "eligiblePositions": [2],
    "id": 2,
    "injuryRequired": false,
    "lineupSlotEligible": true,
    "name": "Running Back",
    "parentId": 3,
    "starter": true
  }, {
    "abbrev": "RB/WR",
    "active": true,
    "bench": false,
    "canApplyLimitIndividually": false,
    "display": true,
    "displayOrder": 4,
    "eligiblePositions": [2, 3],
    "id": 3,
    "injuryRequired": false,
    "lineupSlotEligible": true,
    "name": "Running Back/Wide Receiver",
    "parentId": 7,
    "starter": true
  }, {
    "abbrev": "WR",
    "active": true,
    "bench": false,
    "canApplyLimitIndividually": false,
    "display": true,
    "displayOrder": 5,
    "eligiblePositions": [3],
    "id": 4,
    "injuryRequired": false,
    "lineupSlotEligible": true,
    "name": "Wide Receiver",
    "parentId": 5,
    "starter": true
  }, {
    "abbrev": "WR/TE",
    "active": true,
    "bench": false,
    "canApplyLimitIndividually": false,
    "display": true,
    "displayOrder": 6,
    "eligiblePositions": [3, 4],
    "id": 5,
    "injuryRequired": false,
    "lineupSlotEligible": true,
    "name": "Wide Receiver/Tight End",
    "parentId": 7,
    "starter": true
  }, {
    "abbrev": "TE",
    "active": true,
    "bench": false,
    "canApplyLimitIndividually": false,
    "display": true,
    "displayOrder": 7,
    "eligiblePositions": [4],
    "id": 6,
    "injuryRequired": false,
    "lineupSlotEligible": true,
    "name": "Tight End",
    "parentId": 5,
    "starter": true
  }, {
    "abbrev": "OP",
    "active": true,
    "bench": false,
    "canApplyLimitIndividually": false,
    "display": true,
    "displayOrder": 9,
    "eligiblePositions": [1, 2, 3, 4],
    "id": 7,
    "injuryRequired": false,
    "lineupSlotEligible": true,
    "name": "Offensive Player Utility",
    "parentId": 25,
    "starter": true
  }, {
    "abbrev": "DT",
    "active": true,
    "bench": false,
    "canApplyLimitIndividually": false,
    "display": true,
    "displayOrder": 10,
    "eligiblePositions": [9],
    "id": 8,
    "injuryRequired": false,
    "lineupSlotEligible": true,
    "name": "Defensive Tackle",
    "parentId": 11,
    "starter": true
  }, {
    "abbrev": "DE",
    "active": true,
    "bench": false,
    "canApplyLimitIndividually": false,
    "display": true,
    "displayOrder": 11,
    "eligiblePositions": [10],
    "id": 9,
    "injuryRequired": false,
    "lineupSlotEligible": true,
    "name": "Defensive End",
    "parentId": 11,
    "starter": true
  }, {
    "abbrev": "LB",
    "active": true,
    "bench": false,
    "canApplyLimitIndividually": false,
    "display": true,
    "displayOrder": 12,
    "eligiblePositions": [11],
    "id": 10,
    "injuryRequired": false,
    "lineupSlotEligible": true,
    "name": "Linebacker",
    "parentId": 11,
    "starter": true
  }, {
    "abbrev": "DL",
    "active": true,
    "bench": false,
    "canApplyLimitIndividually": false,
    "display": true,
    "displayOrder": 14,
    "eligiblePositions": [9, 10],
    "id": 11,
    "injuryRequired": false,
    "lineupSlotEligible": true,
    "name": "Defensive Line",
    "parentId": 15,
    "starter": true
  }, {
    "abbrev": "CB",
    "active": true,
    "bench": false,
    "canApplyLimitIndividually": false,
    "display": true,
    "displayOrder": 15,
    "eligiblePositions": [12],
    "id": 12,
    "injuryRequired": false,
    "lineupSlotEligible": true,
    "name": "Cornerback",
    "parentId": 14,
    "starter": true
  }, {
    "abbrev": "S",
    "active": true,
    "bench": false,
    "canApplyLimitIndividually": false,
    "display": true,
    "displayOrder": 16,
    "eligiblePositions": [13],
    "id": 13,
    "injuryRequired": false,
    "lineupSlotEligible": true,
    "name": "Safety",
    "parentId": 14,
    "starter": true
  }, {
    "abbrev": "DB",
    "active": true,
    "bench": false,
    "canApplyLimitIndividually": false,
    "display": true,
    "displayOrder": 17,
    "eligiblePositions": [12, 13],
    "id": 14,
    "injuryRequired": false,
    "lineupSlotEligible": true,
    "name": "Defensive Back",
    "parentId": 15,
    "starter": true
  }, {
    "abbrev": "DP",
    "active": true,
    "bench": false,
    "canApplyLimitIndividually": false,
    "display": true,
    "displayOrder": 18,
    "eligiblePositions": [9, 10, 11, 12, 13],
    "id": 15,
    "injuryRequired": false,
    "lineupSlotEligible": true,
    "name": "Defensive Player Utility",
    "parentId": 25,
    "starter": true
  }, {
    "abbrev": "D/ST",
    "active": true,
    "bench": false,
    "canApplyLimitIndividually": false,
    "display": true,
    "displayOrder": 19,
    "eligiblePositions": [16],
    "id": 16,
    "injuryRequired": false,
    "lineupSlotEligible": true,
    "name": "Team Defense/Special Teams",
    "parentId": 25,
    "starter": true
  }, {
    "abbrev": "K",
    "active": true,
    "bench": false,
    "canApplyLimitIndividually": false,
    "display": true,
    "displayOrder": 20,
    "eligiblePositions": [5],
    "id": 17,
    "injuryRequired": false,
    "lineupSlotEligible": true,
    "name": "Place Kicker",
    "parentId": 7,
    "starter": true
  }, {
    "abbrev": "P",
    "active": true,
    "bench": false,
    "canApplyLimitIndividually": false,
    "display": true,
    "displayOrder": 21,
    "eligiblePositions": [7],
    "id": 18,
    "injuryRequired": false,
    "lineupSlotEligible": true,
    "name": "Punter",
    "parentId": 7,
    "starter": true
  }, {
    "abbrev": "HC",
    "active": true,
    "bench": false,
    "canApplyLimitIndividually": false,
    "display": true,
    "displayOrder": 22,
    "eligiblePositions": [14],
    "id": 19,
    "injuryRequired": false,
    "lineupSlotEligible": true,
    "name": "Head Coach",
    "parentId": 25,
    "starter": true
  }, {
    "abbrev": "BE",
    "active": false,
    "bench": true,
    "canApplyLimitIndividually": false,
    "display": true,
    "displayOrder": 23,
    "eligiblePositions": [1, 2, 3, 4, 5, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17],
    "id": 20,
    "injuryRequired": false,
    "lineupSlotEligible": true,
    "name": "Bench",
    "parentId": 25,
    "starter": false
  }, {
    "abbrev": "IR",
    "active": false,
    "bench": false,
    "canApplyLimitIndividually": false,
    "display": true,
    "displayOrder": 24,
    "eligiblePositions": [1, 2, 3, 4, 5, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17],
    "id": 21,
    "injuryRequired": true,
    "lineupSlotEligible": true,
    "name": "Injured Reserve",
    "parentId": 25,
    "starter": false
  }, {
    "abbrev": "INV",
    "active": false,
    "bench": false,
    "canApplyLimitIndividually": false,
    "display": false,
    "displayOrder": 25,
    "eligiblePositions": [],
    "id": 22,
    "injuryRequired": false,
    "lineupSlotEligible": false,
    "name": "Invalid Player",
    "parentId": 25,
    "starter": false
  }, {
    "abbrev": "FLEX",
    "active": true,
    "bench": false,
    "canApplyLimitIndividually": false,
    "display": true,
    "displayOrder": 8,
    "eligiblePositions": [2, 3, 4],
    "id": 23,
    "injuryRequired": false,
    "lineupSlotEligible": true,
    "name": "Flex",
    "parentId": 7,
    "starter": true
  }, {
    "abbrev": "EDR",
    "active": true,
    "bench": false,
    "canApplyLimitIndividually": false,
    "display": true,
    "displayOrder": 13,
    "eligiblePositions": [17],
    "id": 24,
    "injuryRequired": false,
    "lineupSlotEligible": true,
    "name": "Edge Rusher",
    "parentId": 15,
    "starter": true
  }, {
    "abbrev": "ALL",
    "active": true,
    "bench": false,
    "canApplyLimitIndividually": true,
    "display": true,
    "displayOrder": 0,
    "eligiblePositions": [1, 2, 3, 4, 5, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17],
    "id": 25,
    "injuryRequired": false,
    "lineupSlotEligible": false,
    "name": "All Players",
    "parentId": 25,
    "starter": false
  }],
  "lineupSlotsMap": {
    "0": {
      "abbrev": "QB",
      "active": true,
      "bench": false,
      "canApplyLimitIndividually": false,
      "display": true,
      "displayOrder": 1,
      "eligiblePositions": [1],
      "id": 0,
      "injuryRequired": false,
      "lineupSlotEligible": true,
      "name": "Quarterback",
      "parentId": 7,
      "starter": true
    },
    "1": {
      "abbrev": "TQB",
      "active": true,
      "bench": false,
      "canApplyLimitIndividually": false,
      "display": true,
      "displayOrder": 2,
      "eligiblePositions": [15],
      "id": 1,
      "injuryRequired": false,
      "lineupSlotEligible": true,
      "name": "Team Quarterback",
      "parentId": 7,
      "starter": true
    },
    "2": {
      "abbrev": "RB",
      "active": true,
      "bench": false,
      "canApplyLimitIndividually": false,
      "display": true,
      "displayOrder": 3,
      "eligiblePositions": [2],
      "id": 2,
      "injuryRequired": false,
      "lineupSlotEligible": true,
      "name": "Running Back",
      "parentId": 3,
      "starter": true
    },
    "3": {
      "abbrev": "RB/WR",
      "active": true,
      "bench": false,
      "canApplyLimitIndividually": false,
      "display": true,
      "displayOrder": 4,
      "eligiblePositions": [2, 3],
      "id": 3,
      "injuryRequired": false,
      "lineupSlotEligible": true,
      "name": "Running Back/Wide Receiver",
      "parentId": 7,
      "starter": true
    },
    "4": {
      "abbrev": "WR",
      "active": true,
      "bench": false,
      "canApplyLimitIndividually": false,
      "display": true,
      "displayOrder": 5,
      "eligiblePositions": [3],
      "id": 4,
      "injuryRequired": false,
      "lineupSlotEligible": true,
      "name": "Wide Receiver",
      "parentId": 5,
      "starter": true
    },
    "5": {
      "abbrev": "WR/TE",
      "active": true,
      "bench": false,
      "canApplyLimitIndividually": false,
      "display": true,
      "displayOrder": 6,
      "eligiblePositions": [3, 4],
      "id": 5,
      "injuryRequired": false,
      "lineupSlotEligible": true,
      "name": "Wide Receiver/Tight End",
      "parentId": 7,
      "starter": true
    },
    "6": {
      "abbrev": "TE",
      "active": true,
      "bench": false,
      "canApplyLimitIndividually": false,
      "display": true,
      "displayOrder": 7,
      "eligiblePositions": [4],
      "id": 6,
      "injuryRequired": false,
      "lineupSlotEligible": true,
      "name": "Tight End",
      "parentId": 5,
      "starter": true
    },
    "7": {
      "abbrev": "OP",
      "active": true,
      "bench": false,
      "canApplyLimitIndividually": false,
      "display": true,
      "displayOrder": 9,
      "eligiblePositions": [1, 2, 3, 4],
      "id": 7,
      "injuryRequired": false,
      "lineupSlotEligible": true,
      "name": "Offensive Player Utility",
      "parentId": 25,
      "starter": true
    },
    "8": {
      "abbrev": "DT",
      "active": true,
      "bench": false,
      "canApplyLimitIndividually": false,
      "display": true,
      "displayOrder": 10,
      "eligiblePositions": [9],
      "id": 8,
      "injuryRequired": false,
      "lineupSlotEligible": true,
      "name": "Defensive Tackle",
      "parentId": 11,
      "starter": true
    },
    "9": {
      "abbrev": "DE",
      "active": true,
      "bench": false,
      "canApplyLimitIndividually": false,
      "display": true,
      "displayOrder": 11,
      "eligiblePositions": [10],
      "id": 9,
      "injuryRequired": false,
      "lineupSlotEligible": true,
      "name": "Defensive End",
      "parentId": 11,
      "starter": true
    },
    "10": {
      "abbrev": "LB",
      "active": true,
      "bench": false,
      "canApplyLimitIndividually": false,
      "display": true,
      "displayOrder": 12,
      "eligiblePositions": [11],
      "id": 10,
      "injuryRequired": false,
      "lineupSlotEligible": true,
      "name": "Linebacker",
      "parentId": 11,
      "starter": true
    },
    "11": {
      "abbrev": "DL",
      "active": true,
      "bench": false,
      "canApplyLimitIndividually": false,
      "display": true,
      "displayOrder": 14,
      "eligiblePositions": [9, 10],
      "id": 11,
      "injuryRequired": false,
      "lineupSlotEligible": true,
      "name": "Defensive Line",
      "parentId": 15,
      "starter": true
    },
    "12": {
      "abbrev": "CB",
      "active": true,
      "bench": false,
      "canApplyLimitIndividually": false,
      "display": true,
      "displayOrder": 15,
      "eligiblePositions": [12],
      "id": 12,
      "injuryRequired": false,
      "lineupSlotEligible": true,
      "name": "Cornerback",
      "parentId": 14,
      "starter": true
    },
    "13": {
      "abbrev": "S",
      "active": true,
      "bench": false,
      "canApplyLimitIndividually": false,
      "display": true,
      "displayOrder": 16,
      "eligiblePositions": [13],
      "id": 13,
      "injuryRequired": false,
      "lineupSlotEligible": true,
      "name": "Safety",
      "parentId": 14,
      "starter": true
    },
    "14": {
      "abbrev": "DB",
      "active": true,
      "bench": false,
      "canApplyLimitIndividually": false,
      "display": true,
      "displayOrder": 17,
      "eligiblePositions": [12, 13],
      "id": 14,
      "injuryRequired": false,
      "lineupSlotEligible": true,
      "name": "Defensive Back",
      "parentId": 15,
      "starter": true
    },
    "15": {
      "abbrev": "DP",
      "active": true,
      "bench": false,
      "canApplyLimitIndividually": false,
      "display": true,
      "displayOrder": 18,
      "eligiblePositions": [9, 10, 11, 12, 13],
      "id": 15,
      "injuryRequired": false,
      "lineupSlotEligible": true,
      "name": "Defensive Player Utility",
      "parentId": 25,
      "starter": true
    },
    "16": {
      "abbrev": "D/ST",
      "active": true,
      "bench": false,
      "canApplyLimitIndividually": false,
      "display": true,
      "displayOrder": 19,
      "eligiblePositions": [16],
      "id": 16,
      "injuryRequired": false,
      "lineupSlotEligible": true,
      "name": "Team Defense/Special Teams",
      "parentId": 25,
      "starter": true
    },
    "17": {
      "abbrev": "K",
      "active": true,
      "bench": false,
      "canApplyLimitIndividually": false,
      "display": true,
      "displayOrder": 20,
      "eligiblePositions": [5],
      "id": 17,
      "injuryRequired": false,
      "lineupSlotEligible": true,
      "name": "Place Kicker",
      "parentId": 7,
      "starter": true
    },
    "18": {
      "abbrev": "P",
      "active": true,
      "bench": false,
      "canApplyLimitIndividually": false,
      "display": true,
      "displayOrder": 21,
      "eligiblePositions": [7],
      "id": 18,
      "injuryRequired": false,
      "lineupSlotEligible": true,
      "name": "Punter",
      "parentId": 7,
      "starter": true
    },
    "19": {
      "abbrev": "HC",
      "active": true,
      "bench": false,
      "canApplyLimitIndividually": false,
      "display": true,
      "displayOrder": 22,
      "eligiblePositions": [14],
      "id": 19,
      "injuryRequired": false,
      "lineupSlotEligible": true,
      "name": "Head Coach",
      "parentId": 25,
      "starter": true
    },
    "20": {
      "abbrev": "BE",
      "active": false,
      "bench": true,
      "canApplyLimitIndividually": false,
      "display": true,
      "displayOrder": 23,
      "eligiblePositions": [1, 2, 3, 4, 5, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17],
      "id": 20,
      "injuryRequired": false,
      "lineupSlotEligible": true,
      "name": "Bench",
      "parentId": 25,
      "starter": false
    },
    "21": {
      "abbrev": "IR",
      "active": false,
      "bench": false,
      "canApplyLimitIndividually": false,
      "display": true,
      "displayOrder": 24,
      "eligiblePositions": [1, 2, 3, 4, 5, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17],
      "id": 21,
      "injuryRequired": true,
      "lineupSlotEligible": true,
      "name": "Injured Reserve",
      "parentId": 25,
      "starter": false
    },
    "22": {
      "abbrev": "INV",
      "active": false,
      "bench": false,
      "canApplyLimitIndividually": false,
      "display": false,
      "displayOrder": 25,
      "eligiblePositions": [],
      "id": 22,
      "injuryRequired": false,
      "lineupSlotEligible": false,
      "name": "Invalid Player",
      "parentId": 25,
      "starter": false
    },
    "23": {
      "abbrev": "FLEX",
      "active": true,
      "bench": false,
      "canApplyLimitIndividually": false,
      "display": true,
      "displayOrder": 8,
      "eligiblePositions": [2, 3, 4],
      "id": 23,
      "injuryRequired": false,
      "lineupSlotEligible": true,
      "name": "Flex",
      "parentId": 7,
      "starter": true
    },
    "24": {
      "abbrev": "EDR",
      "active": true,
      "bench": false,
      "canApplyLimitIndividually": false,
      "display": true,
      "displayOrder": 13,
      "eligiblePositions": [17],
      "id": 24,
      "injuryRequired": false,
      "lineupSlotEligible": true,
      "name": "Edge Rusher",
      "parentId": 15,
      "starter": true
    },
    "25": {
      "abbrev": "ALL",
      "active": true,
      "bench": false,
      "canApplyLimitIndividually": true,
      "display": true,
      "displayOrder": 0,
      "eligiblePositions": [1, 2, 3, 4, 5, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17],
      "id": 25,
      "injuryRequired": false,
      "lineupSlotEligible": false,
      "name": "All Players",
      "parentId": 25,
      "starter": false
    }
  },
  "positions": [{
    "abbrev": "POS0",
    "active": true,
    "display": false,
    "displayOrder": 0,
    "id": 0,
    "name": "POS0",
    "parentId": 0,
    "statCategoryId": 0
  }, {
    "abbrev": "QB",
    "active": true,
    "display": true,
    "displayOrder": 1,
    "id": 1,
    "name": "Quarterback",
    "parentId": 0,
    "statCategoryId": 0
  }, {
    "abbrev": "RB",
    "active": true,
    "display": true,
    "displayOrder": 2,
    "id": 2,
    "name": "Running Back",
    "parentId": 0,
    "statCategoryId": 0
  }, {
    "abbrev": "WR",
    "active": true,
    "display": true,
    "displayOrder": 3,
    "id": 3,
    "name": "Wide Receiver",
    "parentId": 0,
    "statCategoryId": 0
  }, {
    "abbrev": "TE",
    "active": true,
    "display": true,
    "displayOrder": 4,
    "id": 4,
    "name": "Tight End",
    "parentId": 0,
    "statCategoryId": 0
  }, {
    "abbrev": "K",
    "active": true,
    "display": true,
    "displayOrder": 5,
    "id": 5,
    "name": "Place Kicker",
    "parentId": 0,
    "statCategoryId": 3
  }, {
    "abbrev": "POS6",
    "active": true,
    "display": false,
    "displayOrder": 6,
    "id": 6,
    "name": "POS6",
    "parentId": 0,
    "statCategoryId": 0
  }, {
    "abbrev": "P",
    "active": true,
    "display": true,
    "displayOrder": 7,
    "id": 7,
    "name": "Punter",
    "parentId": 0,
    "statCategoryId": 2
  }, {
    "abbrev": "POS8",
    "active": true,
    "display": false,
    "displayOrder": 8,
    "id": 8,
    "name": "POS8",
    "parentId": 0,
    "statCategoryId": 0
  }, {
    "abbrev": "DT",
    "active": true,
    "display": true,
    "displayOrder": 9,
    "id": 9,
    "name": "Defensive Tackle",
    "parentId": 0,
    "statCategoryId": 1
  }, {
    "abbrev": "DE",
    "active": true,
    "display": true,
    "displayOrder": 10,
    "id": 10,
    "name": "Defensive End",
    "parentId": 0,
    "statCategoryId": 1
  }, {
    "abbrev": "LB",
    "active": true,
    "display": true,
    "displayOrder": 11,
    "id": 11,
    "name": "Linebacker",
    "parentId": 0,
    "statCategoryId": 1
  }, {
    "abbrev": "CB",
    "active": true,
    "display": true,
    "displayOrder": 12,
    "id": 12,
    "name": "Cornerback",
    "parentId": 0,
    "statCategoryId": 1
  }, {
    "abbrev": "S",
    "active": true,
    "display": true,
    "displayOrder": 13,
    "id": 13,
    "name": "Safety",
    "parentId": 0,
    "statCategoryId": 1
  }, {
    "abbrev": "HC",
    "active": true,
    "display": true,
    "displayOrder": 14,
    "id": 14,
    "name": "Head Coach",
    "parentId": 0,
    "statCategoryId": 4
  }, {
    "abbrev": "TQB",
    "active": true,
    "display": true,
    "displayOrder": 15,
    "id": 15,
    "name": "Team Quarterback",
    "parentId": 0,
    "statCategoryId": 0
  }, {
    "abbrev": "D/ST",
    "active": true,
    "display": true,
    "displayOrder": 16,
    "id": 16,
    "name": "Team Defense/Special Teams",
    "parentId": 0,
    "statCategoryId": 5
  }, {
    "abbrev": "EDR",
    "active": true,
    "display": true,
    "displayOrder": 17,
    "id": 17,
    "name": "Edge Rusher",
    "parentId": 0,
    "statCategoryId": 1
  }],
  "proTeams": [{
    "abbrev": "FA",
    "byeWeek": 0,
    "id": 0,
    "location": "",
    "name": "FA",
    "universeId": 0
  }, {
    "abbrev": "Atl",
    "byeWeek": 10,
    "id": 1,
    "location": "Atlanta",
    "name": "Falcons",
    "universeId": 2
  }, {
    "abbrev": "Buf",
    "byeWeek": 11,
    "id": 2,
    "location": "Buffalo",
    "name": "Bills",
    "universeId": 1
  }, {
    "abbrev": "Chi",
    "byeWeek": 11,
    "id": 3,
    "location": "Chicago",
    "name": "Bears",
    "universeId": 2
  }, {
    "abbrev": "Cin",
    "byeWeek": 9,
    "id": 4,
    "location": "Cincinnati",
    "name": "Bengals",
    "universeId": 1
  }, {
    "abbrev": "Cle",
    "byeWeek": 9,
    "id": 5,
    "location": "Cleveland",
    "name": "Browns",
    "universeId": 1
  }, {
    "abbrev": "Dal",
    "byeWeek": 10,
    "id": 6,
    "location": "Dallas",
    "name": "Cowboys",
    "universeId": 2
  }, {
    "abbrev": "Den",
    "byeWeek": 8,
    "id": 7,
    "location": "Denver",
    "name": "Broncos",
    "universeId": 1
  }, {
    "abbrev": "Det",
    "byeWeek": 5,
    "id": 8,
    "location": "Detroit",
    "name": "Lions",
    "universeId": 2
  }, {
    "abbrev": "GB",
    "byeWeek": 5,
    "id": 9,
    "location": "Green Bay",
    "name": "Packers",
    "universeId": 2
  }, {
    "abbrev": "Ten",
    "byeWeek": 7,
    "id": 10,
    "location": "Tennessee",
    "name": "Titans",
    "universeId": 1
  }, {
    "abbrev": "Ind",
    "byeWeek": 7,
    "id": 11,
    "location": "Indianapolis",
    "name": "Colts",
    "universeId": 1
  }, {
    "abbrev": "KC",
    "byeWeek": 10,
    "id": 12,
    "location": "Kansas City",
    "name": "Chiefs",
    "universeId": 1
  }, {
    "abbrev": "LV",
    "byeWeek": 6,
    "id": 13,
    "location": "Las Vegas",
    "name": "Raiders",
    "universeId": 1
  }, {
    "abbrev": "LAR",
    "byeWeek": 9,
    "id": 14,
    "location": "Los Angeles",
    "name": "Rams",
    "universeId": 2
  }, {
    "abbrev": "Mia",
    "byeWeek": 11,
    "id": 15,
    "location": "Miami",
    "name": "Dolphins",
    "universeId": 1
  }, {
    "abbrev": "Min",
    "byeWeek": 7,
    "id": 16,
    "location": "Minnesota",
    "name": "Vikings",
    "universeId": 2
  }, {
    "abbrev": "NE",
    "byeWeek": 6,
    "id": 17,
    "location": "New England",
    "name": "Patriots",
    "universeId": 1
  }, {
    "abbrev": "NO",
    "byeWeek": 6,
    "id": 18,
    "location": "New Orleans",
    "name": "Saints",
    "universeId": 2
  }, {
    "abbrev": "NYG",
    "byeWeek": 11,
    "id": 19,
    "location": "New York",
    "name": "Giants",
    "universeId": 2
  }, {
    "abbrev": "NYJ",
    "byeWeek": 11,
    "id": 20,
    "location": "New York",
    "name": "Jets",
    "universeId": 1
  }, {
    "abbrev": "Phi",
    "byeWeek": 9,
    "id": 21,
    "location": "Philadelphia",
    "name": "Eagles",
    "universeId": 2
  }, {
    "abbrev": "Ari",
    "byeWeek": 8,
    "id": 22,
    "location": "Arizona",
    "name": "Cardinals",
    "universeId": 2
  }, {
    "abbrev": "Pit",
    "byeWeek": 8,
    "id": 23,
    "location": "Pittsburgh",
    "name": "Steelers",
    "universeId": 1
  }, {
    "abbrev": "LAC",
    "byeWeek": 10,
    "id": 24,
    "location": "Los Angeles",
    "name": "Chargers",
    "universeId": 1
  }, {
    "abbrev": "SF",
    "byeWeek": 11,
    "id": 25,
    "location": "San Francisco",
    "name": "49ers",
    "universeId": 2
  }, {
    "abbrev": "Sea",
    "byeWeek": 6,
    "id": 26,
    "location": "Seattle",
    "name": "Seahawks",
    "universeId": 2
  }, {
    "abbrev": "TB",
    "byeWeek": 13,
    "id": 27,
    "location": "Tampa Bay",
    "name": "Buccaneers",
    "universeId": 2
  }, {
    "abbrev": "Wsh",
    "byeWeek": 8,
    "id": 28,
    "location": "Washington",
    "name": "",
    "universeId": 2
  }, {
    "abbrev": "Car",
    "byeWeek": 13,
    "id": 29,
    "location": "Carolina",
    "name": "Panthers",
    "universeId": 2
  }, {
    "abbrev": "Jax",
    "byeWeek": 7,
    "id": 30,
    "location": "Jacksonville",
    "name": "Jaguars",
    "universeId": 1
  }, {
    "abbrev": "Bal",
    "byeWeek": 8,
    "id": 33,
    "location": "Baltimore",
    "name": "Ravens",
    "universeId": 1
  }, {
    "abbrev": "Hou",
    "byeWeek": 8,
    "id": 34,
    "location": "Houston",
    "name": "Texans",
    "universeId": 1
  }],
  "proTeamsMap": {
    "0": {
      "abbrev": "FA",
      "byeWeek": 0,
      "id": 0,
      "location": "",
      "name": "FA",
      "universeId": 0
    },
    "1": {
      "abbrev": "Atl",
      "byeWeek": 10,
      "id": 1,
      "location": "Atlanta",
      "name": "Falcons",
      "universeId": 2
    },
    "2": {
      "abbrev": "Buf",
      "byeWeek": 11,
      "id": 2,
      "location": "Buffalo",
      "name": "Bills",
      "universeId": 1
    },
    "3": {
      "abbrev": "Chi",
      "byeWeek": 11,
      "id": 3,
      "location": "Chicago",
      "name": "Bears",
      "universeId": 2
    },
    "4": {
      "abbrev": "Cin",
      "byeWeek": 9,
      "id": 4,
      "location": "Cincinnati",
      "name": "Bengals",
      "universeId": 1
    },
    "5": {
      "abbrev": "Cle",
      "byeWeek": 9,
      "id": 5,
      "location": "Cleveland",
      "name": "Browns",
      "universeId": 1
    },
    "6": {
      "abbrev": "Dal",
      "byeWeek": 10,
      "id": 6,
      "location": "Dallas",
      "name": "Cowboys",
      "universeId": 2
    },
    "7": {
      "abbrev": "Den",
      "byeWeek": 8,
      "id": 7,
      "location": "Denver",
      "name": "Broncos",
      "universeId": 1
    },
    "8": {
      "abbrev": "Det",
      "byeWeek": 5,
      "id": 8,
      "location": "Detroit",
      "name": "Lions",
      "universeId": 2
    },
    "9": {
      "abbrev": "GB",
      "byeWeek": 5,
      "id": 9,
      "location": "Green Bay",
      "name": "Packers",
      "universeId": 2
    },
    "10": {
      "abbrev": "Ten",
      "byeWeek": 7,
      "id": 10,
      "location": "Tennessee",
      "name": "Titans",
      "universeId": 1
    },
    "11": {
      "abbrev": "Ind",
      "byeWeek": 7,
      "id": 11,
      "location": "Indianapolis",
      "name": "Colts",
      "universeId": 1
    },
    "12": {
      "abbrev": "KC",
      "byeWeek": 10,
      "id": 12,
      "location": "Kansas City",
      "name": "Chiefs",
      "universeId": 1
    },
    "13": {
      "abbrev": "LV",
      "byeWeek": 6,
      "id": 13,
      "location": "Las Vegas",
      "name": "Raiders",
      "universeId": 1
    },
    "14": {
      "abbrev": "LAR",
      "byeWeek": 9,
      "id": 14,
      "location": "Los Angeles",
      "name": "Rams",
      "universeId": 2
    },
    "15": {
      "abbrev": "Mia",
      "byeWeek": 11,
      "id": 15,
      "location": "Miami",
      "name": "Dolphins",
      "universeId": 1
    },
    "16": {
      "abbrev": "Min",
      "byeWeek": 7,
      "id": 16,
      "location": "Minnesota",
      "name": "Vikings",
      "universeId": 2
    },
    "17": {
      "abbrev": "NE",
      "byeWeek": 6,
      "id": 17,
      "location": "New England",
      "name": "Patriots",
      "universeId": 1
    },
    "18": {
      "abbrev": "NO",
      "byeWeek": 6,
      "id": 18,
      "location": "New Orleans",
      "name": "Saints",
      "universeId": 2
    },
    "19": {
      "abbrev": "NYG",
      "byeWeek": 11,
      "id": 19,
      "location": "New York",
      "name": "Giants",
      "universeId": 2
    },
    "20": {
      "abbrev": "NYJ",
      "byeWeek": 11,
      "id": 20,
      "location": "New York",
      "name": "Jets",
      "universeId": 1
    },
    "21": {
      "abbrev": "Phi",
      "byeWeek": 9,
      "id": 21,
      "location": "Philadelphia",
      "name": "Eagles",
      "universeId": 2
    },
    "22": {
      "abbrev": "Ari",
      "byeWeek": 8,
      "id": 22,
      "location": "Arizona",
      "name": "Cardinals",
      "universeId": 2
    },
    "23": {
      "abbrev": "Pit",
      "byeWeek": 8,
      "id": 23,
      "location": "Pittsburgh",
      "name": "Steelers",
      "universeId": 1
    },
    "24": {
      "abbrev": "LAC",
      "byeWeek": 10,
      "id": 24,
      "location": "Los Angeles",
      "name": "Chargers",
      "universeId": 1
    },
    "25": {
      "abbrev": "SF",
      "byeWeek": 11,
      "id": 25,
      "location": "San Francisco",
      "name": "49ers",
      "universeId": 2
    },
    "26": {
      "abbrev": "Sea",
      "byeWeek": 6,
      "id": 26,
      "location": "Seattle",
      "name": "Seahawks",
      "universeId": 2
    },
    "27": {
      "abbrev": "TB",
      "byeWeek": 13,
      "id": 27,
      "location": "Tampa Bay",
      "name": "Buccaneers",
      "universeId": 2
    },
    "28": {
      "abbrev": "Wsh",
      "byeWeek": 8,
      "id": 28,
      "location": "Washington",
      "name": "",
      "universeId": 2
    },
    "29": {
      "abbrev": "Car",
      "byeWeek": 13,
      "id": 29,
      "location": "Carolina",
      "name": "Panthers",
      "universeId": 2
    },
    "30": {
      "abbrev": "Jax",
      "byeWeek": 7,
      "id": 30,
      "location": "Jacksonville",
      "name": "Jaguars",
      "universeId": 1
    },
    "33": {
      "abbrev": "Bal",
      "byeWeek": 8,
      "id": 33,
      "location": "Baltimore",
      "name": "Ravens",
      "universeId": 1
    },
    "34": {
      "abbrev": "Hou",
      "byeWeek": 8,
      "id": 34,
      "location": "Houston",
      "name": "Texans",
      "universeId": 1
    }
  },
}

exports.constants = constants;